# Generated by Django 4.2.7 on 2023-11-15 16:16

import django.contrib.postgres.fields
from django.db import migrations, models
import handlers.table_handler


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=4)),
                ('capacity', models.IntegerField(max_length=4)),
                ('table_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                    max_length=30), default='available', size=None, validators=[handlers.table_handler.validate_status_table])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
