# Generated by Django 4.2.7 on 2023-11-17 02:25

import django.contrib.postgres.fields
from django.db import migrations, models
import handlers.table_handler


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None, validators=[handlers.table_handler.validate_status_table]),
        ),
    ]
