# Generated by Django 4.2.7 on 2023-11-16 04:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import handlers.order_handler


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0002_alter_table_capacity_alter_table_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('process_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default='orderPending', size=None, validators=[handlers.order_handler.validate_status])),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
