# Generated by Django 4.2.7 on 2023-12-06 03:37

import django.contrib.postgres.fields
from django.db import migrations, models
import handlers.order_handler


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['orderPending'], size=None, validators=[handlers.order_handler.validate_status]),
        ),
    ]
