# Generated by Django 4.2.7 on 2023-12-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('orders', '0004_alter_order_process_status'),
        ('details_order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='detailsorder',
            unique_together={('order', 'product')},
        ),
    ]
